Wash notif
iwishiwasaneagle/boxofhope pull request #107
Opened 2021-04-13 20:16 UTC by sarahswinton

Includes: 

- Issue 93: Update CI to include wash tracking tests. 
- Postman Tests Refactor/Update.
- Implementation of mask washing feature: notifications.
- Refactored schema, controller, and route for "settings".

2021-04-13 20:42 UTC, iwishiwasaneagle requested changes

2021-04-13 20:42 UTC, iwishiwasaneagle commented on .github/workflows/api_ci.yml
> +    branches: [main, dev, api-dev, washNotif]
Please delete `washNotif`

2021-04-13 20:42 UTC, iwishiwasaneagle commented on webapp/src/components/pushNotifications/usePushNotifications.js
> +      if(existingSubscriptionPush && existingSubscriptionId==null){
Good catch

2021-04-14 10:23 UTC, sarahswinton commented on .github/workflows/api_ci.yml
> +    branches: [main, dev, api-dev, washNotif]
Good catch, that's it sorted now.

2021-04-14 13:44 UTC, iwishiwasaneagle approved these changes

2021-04-14 13:44 UTC, merged