Api tests
iwishiwasaneagle/boxofhope pull request #108
Opened 2021-04-18 20:24 UTC by sarahswinton

- Added API Testing Documentation functionality using Newman, Postman and Newman's HTMLExtra Reporter.
- Updated API Tests to include response time tests. 
- Updated readme and documentation.

2021-04-18 20:26 UTC, iwishiwasaneagle reviewed
Is this needed?

(eugh thought it would show what file i meant. I was commenting on `api/newman/FinalisedTests-2021-04-18-19-10-22-286-0.html`)

2021-04-18 21:56 UTC, iwishiwasaneagle requested changes
Is the html file needed @sarahswinton ?

2021-04-19 08:00 UTC, sarahswinton commented
> Is the html file needed @sarahswinton ?
I've left it in as an example of the functional API Test Report - would you rather I take it out?

2021-04-19 08:32 UTC, iwishiwasaneagle approved these changes

2021-04-19 08:32 UTC, merged